driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list: test::legacy
  - name: resource_based
    run_list: test::default
  - name: activemq-legacy
    excludes:
      - freebsd-11
      - opensuse-leap-42
    run_list: test::legacy
    verifier:
      inspec_tests:
        - name: activemq-legacy
          path: test/integration/activemq-legacy
      attrs:
        - test/integration/attributes/activemq.yml
  - name: activemq-resource
    excludes:
      - freebsd-11
      - opensuse-leap-42
    run_list: test::default
    verifier:
      inspec_tests:
        - name: activemq-resource
          path: test/integration/activemq-resource
      attrs:
        - test/integration/attributes/activemq.yml
