---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
  run_list: ["recipe[apt]"]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.2.0.box
  run_list: ["recipe[apt]"]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box

suites:
- name: default
  run_list: ["recipe[activemq]"]
  attributes: {}
