source 'https://rubygems.org'

gem 'rake'
gem 'tomlrb'
gem 'foodcritic', '~> 6.2'
gem 'rubocop', '~> 0.38'
gem 'berkshelf', '~> 4.3'
gem 'chefspec', '~> 4.6'
gem 'test-kitchen', '~> 1.7'
gem 'kitchen-inspec', '~> 0.12'
gem 'kitchen-vagrant', '~> 0.20'
gem 'kitchen-dokken'
gem 'stove'
